locals {
  deploy_enabled = var.generate_deploy_bundle
  deploy_dir     = "${path.module}/_out/deploy"
  deploy_template_vars = {
    dashboard_host           = var.pangolin_dashboard_host
    base_domain              = var.pangolin_base_domain
    tunnel_host              = local.tunnel_host
    letsencrypt_email        = var.letsencrypt_email
    server_secret            = random_password.pangolin_secret[0].result
    badger_version           = var.traefik_badger_version
    pangolin_image_tag       = var.pangolin_image_tag
    gerbil_image_tag         = var.gerbil_image_tag
    traefik_image_tag        = var.traefik_image_tag
    enable_integration_api   = var.enable_integration_api
    integration_api_host     = local.integration_api_host
    integration_port         = var.pangolin_integration_port
    integration_api_url            = local.integration_api_url
    enable_crowdsec                = var.enable_crowdsec
    crowdsec_image_tag             = var.crowdsec_image_tag
    traefik_crowdsec_bouncer_version = var.traefik_crowdsec_bouncer_version
  }
}

resource "random_password" "pangolin_secret" {
  count   = local.deploy_enabled ? 1 : 0
  length  = 48
  special = false
}

resource "local_file" "deploy_compose" {
  count = local.deploy_enabled ? 1 : 0

  content = templatefile("${path.module}/templates/deploy/docker-compose.yml.tmpl", local.deploy_template_vars)
  filename             = "${local.deploy_dir}/docker-compose.yml"
  file_permission      = "0644"
  directory_permission = "0755"
}

resource "local_file" "deploy_config" {
  count = local.deploy_enabled ? 1 : 0

  content              = templatefile("${path.module}/templates/deploy/config.yml.tmpl", local.deploy_template_vars)
  filename             = "${local.deploy_dir}/config/config.yml"
  file_permission      = "0640"
  directory_permission = "0755"
}

resource "local_file" "deploy_traefik_static" {
  count = local.deploy_enabled ? 1 : 0

  content              = templatefile("${path.module}/templates/deploy/traefik_config.yml.tmpl", local.deploy_template_vars)
  filename             = "${local.deploy_dir}/config/traefik/traefik_config.yml"
  file_permission      = "0644"
  directory_permission = "0755"
}

resource "local_file" "deploy_traefik_dynamic" {
  count = local.deploy_enabled ? 1 : 0

  content              = templatefile("${path.module}/templates/deploy/traefik_dynamic_config.yml.tmpl", local.deploy_template_vars)
  filename             = "${local.deploy_dir}/config/traefik/dynamic_config.yml"
  file_permission      = "0644"
  directory_permission = "0755"
}

# Placeholder so empty dirs exist before first compose up on the VM.
resource "local_file" "deploy_acme_placeholder" {
  count = local.deploy_enabled ? 1 : 0

  content              = ""
  filename             = "${local.deploy_dir}/config/letsencrypt/.gitkeep"
  file_permission      = "0644"
  directory_permission = "0755"
}

resource "local_file" "deploy_crowdsec_dirs" {
  count = local.deploy_enabled && var.enable_crowdsec ? 1 : 0

  content              = ""
  filename             = "${local.deploy_dir}/config/crowdsec/.gitkeep"
  file_permission      = "0644"
  directory_permission = "0755"
}

resource "local_file" "deploy_crowdsec_db" {
  count = local.deploy_enabled && var.enable_crowdsec ? 1 : 0

  content              = ""
  filename             = "${local.deploy_dir}/config/crowdsec/db/.gitkeep"
  file_permission      = "0644"
  directory_permission = "0755"
}

resource "local_file" "deploy_crowdsec_bouncer_script" {
  count = local.deploy_enabled && var.enable_crowdsec ? 1 : 0

  content              = file("${path.module}/scripts/configure-crowdsec-bouncer.sh")
  filename             = "${local.deploy_dir}/configure-crowdsec-bouncer.sh"
  file_permission      = "0755"
  directory_permission = "0755"
}

resource "local_file" "deploy_vm_install" {
  count = local.deploy_enabled ? 1 : 0

  content              = local.vm_install_script
  filename             = "${local.deploy_dir}/vm-install.sh"
  file_permission      = "0755"
  directory_permission = "0755"
}

resource "local_file" "deploy_readme" {
  count = local.deploy_enabled ? 1 : 0

  content = <<-EOT
    Pangolin deploy bundle (generated by Terraform).
    Push to the VM: ./scripts/push-deploy.sh
    Or set install_pangolin_via_ssh = true in config.auto.tfvars.

    After containers are up:
      https://${var.pangolin_dashboard_host}/auth/initial-setup
    Setup token: terraform output -raw pangolin_setup_token
    ${var.enable_integration_api ? "Integration API: ${local.integration_api_url}/v1 (Swagger: ${local.integration_api_url}/v1/docs)" : ""}
  EOT
  filename             = "${local.deploy_dir}/README.txt"
  file_permission      = "0644"
  directory_permission = "0755"
}